defaults:
  - _self_
  - encoder: default.yaml
  - decoder: ip_adapter.yaml
  - cfm: default.yaml
  - optimizer: adam.yaml

_target_: matcha.models.matcha_tts.MatchaTTS
n_vocab: 7094
n_spks: ${data.n_spks}
spk_emb_dim: 64
n_feats: 80
data_statistics: ${data.data_statistics}
out_size: null # Must be divisible by 4
unconditioned_percentage: 0.15
prior_loss: true
cond_wave: true
